carts:
  name: carts
  replicaCount: 1
  image:
    repository: weaveworksdemos/carts
    tag: 0.4.8
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  env:
    javaOpts: "-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false"
  service:
    port: 80
    targetPort: 80

cartsDb:
  name: carts-db
  replicaCount: 1
  image:
    repository: mongo
    tag: 3.4
  service:
    port: 27017
    targetPort: 27017

catalogue:
  name: catalogue
  replicaCount: 1
  image:
    repository: weaveworksdemos/catalogue
    tag: 0.3.5
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    port: 80
    targetPort: 80
  probe:
    liveness:
      path: /health
      initialDelaySeconds: 300
      periodSeconds: 3
    readiness:
      path: /health
      initialDelaySeconds: 180
      periodSeconds: 3

catalogueDb:
  name: catalogue-db
  replicaCount: 1
  image:
    repository: weaveworksdemos/catalogue-db
    tag: 0.3.0
  env:
    mysqlRootPassword: default_password
    mysqlDatabase: socksdb
  service:
    port: 3306
    targetPort: 3306

frontEnd:
  name: front-end
  replicaCount: 2
  image:
    repository: weaveworksdemos/front-end
    tag: 0.3.12
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  service:
    port: 80
    targetPort: 8079
  probe:
    liveness:
      path: /
      initialDelaySeconds: 300
      periodSeconds: 3
    readiness:
      path: /
      initialDelaySeconds: 30
      periodSeconds: 3
  env:
    sessionRedis: "true"

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nlb.ingress.kubernetes.io/scheme: "internet-facing"
    nlb.ingress.kubernetes.io/target-type: "ip"
    nlb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    # nlb.ingress.kubernetes.io/ssl-redirect: '443'
    # nlb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:eu-central-1:783764588202:certificate/bfbb2ea1-ead3-4dca-ad40-af0ffccfd4ee"
  paths:
    - path: /
      pathType: ImplementationSpecific
  hosts:
    - host: dev.app.monlabo.de
      paths:
        - path: /
          serviceName: front-end
          servicePort: 80
tls:
  enabled: false
  secretName: company-tls-secret
  hosts:
    - example.dev.company.com
    - admin.dev.company.com
    
orders:
  name: orders
  replicaCount: 1
  image:
    repository: weaveworksdemos/orders
    tag: 0.4.7
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  env:
    javaOpts: "-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false"
  service:
    port: 80
    targetPort: 80

ordersDb:
  name: orders-db
  replicaCount: 1
  image:
    repository: mongo
    tag: 3.4
  service:
    port: 27017
    targetPort: 27017

shipping:
  name: shipping
  replicaCount: 1
  image:
    repository: weaveworksdemos/shipping
    tag: 0.4.8
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  service:
    port: 80
    targetPort: 80
  env:
    zipkin: zipkin.jaeger.svc.cluster.local
    javaOpts: "-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false"

queueMaster:
  name: queue-master
  replicaCount: 1
  image:
    repository: weaveworksdemos/queue-master
    tag: 0.3.1
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  service:
    port: 80
    targetPort: 80
  env:
    javaOpts: "-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false"

rabbitmq:
  name: rabbitmq
  replicaCount: 1
  image:
    repository: rabbitmq
    tag: 3.6.8-management
  ports:
    management: 15672
    rabbitmq: 5672
  exporter:
    image:
      repository: kbudde/rabbitmq-exporter
      tag: latest
    port: 9090
  service:
    ports:
      rabbitmq: 5672
      exporter: 9090

# sessionDb:
#   name: session-db
#   replicaCount: 1
#   image:
#     repository: redis
#     tag: alpine
#   service:
#     port: 6379
#     targetPort: 6379

payment:
  name: payment
  replicaCount: 1
  image:
    repository: weaveworksdemos/payment
    tag: 0.4.3
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    port: 80
    targetPort: 80
  probe:
    path: /health
    liveness:
      initialDelaySeconds: 300
      periodSeconds: 3
    readiness:
      initialDelaySeconds: 180
      periodSeconds: 3

user:
  name: user
  replicaCount: 1
  image:
    repository: weaveworksdemos/user
    tag: 0.4.4
    # repository: weaveworksdemos/user
    # tag: v0.1.4
  resources:
    limits:
      cpu: 500m
      memory: 1000Mi
    requests:
      cpu: 300m
      memory: 512Mi
  service:
    port: 80
    targetPort: 80
  env:
    mongo: user-db:27017
  probe:
    path: /health
    liveness:
      initialDelaySeconds: 300
      periodSeconds: 3
    readiness:
      initialDelaySeconds: 180
      periodSeconds: 3

userDb:
  name: user-db
  replicaCount: 1
  image:
    repository: weaveworksdemos/user-db
    tag:  0.4.0
    # repository: weaveworksdemos/user-db
    # tag:  v0.1.4
  service:
    port: 27017
    targetPort: 27017

nodeSelector:
  kubernetes.io/os: linux