carts:
  name: carts
  replicaCount: 1
  image:
    repository: weaveworksdemos/carts
    tag: 0.4.8
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  env:
    javaOpts: "-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false"
  service:
    port: 80
    targetPort: 80

cartsDb:
  name: carts-db
  replicaCount: 1
  image:
    repository: mongo
    tag: 3.6.8
  service:
    port: 27017
    targetPort: 27017

catalogue:
  name: catalogue
  replicaCount: 1
  image:
    repository: 783764588202.dkr.ecr.eu-central-1.amazonaws.com/catalogue
    tag: v0.1.2
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    port: 80
    targetPort: 80
  probe:
    liveness:
      path: /health
      initialDelaySeconds: 300
      periodSeconds: 3
    readiness:
      path: /health
      initialDelaySeconds: 180
      periodSeconds: 3

catalogueDb:
  name: catalogue-db
  replicaCount: 1
  image:
    repository: 783764588202.dkr.ecr.eu-central-1.amazonaws.com/catalogue-db
    tag: v0.1.3
  env:
    mysqlRootPassword: default_password
    mysqlDatabase: socksdb
  service:
    port: 3306
    targetPort: 3306

frontEnd:
  name: front-end
  replicaCount: 1
  image:
    repository: 783764588202.dkr.ecr.eu-central-1.amazonaws.com/front-end
    tag: v0.1.2
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  service:
    port: 80
    targetPort: 8079
  probe:
    liveness:
      path: /
      initialDelaySeconds: 300
      periodSeconds: 3
    readiness:
      path: /
      initialDelaySeconds: 30
      periodSeconds: 3
  env:
    sessionRedis: "true"

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nlb.ingress.kubernetes.io/scheme: "internet-facing"
    nlb.ingress.kubernetes.io/target-type: "ip"
    nlb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    nlb.ingress.kubernetes.io/ssl-redirect: '443'
    nlb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:eu-central-1:783764588202:certificate/bfbb2ea1-ead3-4dca-ad40-af0ffccfd4ee"
  paths:
    - path: /
      pathType: ImplementationSpecific
  hosts:
    - host: dev.app.monlabo.de
      paths:
        - path: /
          serviceName: front-end
          servicePort: 80

orders:
  name: orders
  replicaCount: 1
  image:
    repository: 783764588202.dkr.ecr.eu-central-1.amazonaws.com/orders
    tag: v0.1.2
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  env:
    javaOpts: "-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false"
  service:
    port: 80
    targetPort: 80

ordersDb:
  name: orders-db
  replicaCount: 1
  image:
    repository: mongo
    tag: 3.6.8
  service:
    port: 27017
    targetPort: 27017

payment:
  name: payment
  replicaCount: 1
  image:
    repository: 783764588202.dkr.ecr.eu-central-1.amazonaws.com/payment
    tag: v0.1.2
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    port: 80
    targetPort: 80
  probe:
    path: /health
    liveness:
      initialDelaySeconds: 300
      periodSeconds: 3
    readiness:
      initialDelaySeconds: 180
      periodSeconds: 3

queueMaster:
  name: queue-master
  replicaCount: 1
  image:
    repository: 783764588202.dkr.ecr.eu-central-1.amazonaws.com/queue-master
    tag: v0.1.2
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  service:
    port: 80
    targetPort: 80
  env:
    javaOpts: "-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false"

rabbitmq:
  name: rabbitmq
  replicaCount: 1
  image:
    repository: rabbitmq
    tag: 3.6.8-management
  ports:
    management: 15672
    rabbitmq: 5672
  exporter:
    image:
      repository: kbudde/rabbitmq-exporter
      tag: latest
    port: 9090
  service:
    ports:
      rabbitmq: 5672
      exporter: 9090

sessionDb:
  name: session-db
  replicaCount: 1
  image:
    repository: redis
    tag: alpine
  service:
    port: 6379
    targetPort: 6379

shipping:
  name: shipping
  replicaCount: 1
  image:
    repository: 783764588202.dkr.ecr.eu-central-1.amazonaws.com/shipping
    tag: v0.1.2
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  service:
    port: 80
    targetPort: 80
  env:
    zipkin: zipkin.jaeger.svc.cluster.local
    javaOpts: "-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false"


user:
  name: user
  replicaCount: 1
  image:
    repository: 783764588202.dkr.ecr.eu-central-1.amazonaws.com/user
    tag: v0.1.3
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  service:
    port: 80
    targetPort: 80
  env:
    mongo: user-db:27017
  probe:
    path: /health
    liveness:
      initialDelaySeconds: 300
      periodSeconds: 3
    readiness:
      initialDelaySeconds: 180
      periodSeconds: 3

userDb:
  name: user-db
  replicaCount: 1
  image:
    repository: 783764588202.dkr.ecr.eu-central-1.amazonaws.com/user-db
    tag:  v0.1.2
  service:
    port: 27017
    targetPort: 27017

nodeSelector:
  kubernetes.io/os: linux