apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ordersDb.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    name: {{ .Values.ordersDb.name }}
spec:
  ports:
    - port: {{ .Values.ordersDb.service.port }}
      targetPort: {{ .Values.ordersDb.service.targetPort }}
      protocol: TCP
  selector:
    name: {{ .Values.ordersDb.name }}
