apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.payment.name }}           # {{ .Values.payment.name }} → 'payment'
  namespace: {{ .Release.Namespace }}
  labels:
    name: {{ .Values.payment.name }}         # {{ .Values.payment.name }} → 'payment'
spec:
  replicas: {{ .Values.payment.replicaCount }}  # {{ .Values.payment.replicaCount }} → 1
  selector:
    matchLabels:
      name: {{ .Values.payment.name }}       # {{ .Values.payment.name }} → 'payment'
  template:
    metadata:
      labels:
        name: {{ .Values.payment.name }}     # {{ .Values.payment.name }} → 'payment'
    spec:
      containers:
        - name: {{ .Values.payment.name }}   # {{ .Values.payment.name }} → 'payment'
          image: "{{ .Values.payment.image.repository }}:{{ .Values.payment.image.tag }}"  # f3lin/payment:v0.1.2
          resources:
            {{- toYaml .Values.payment.resources | nindent 12 }}  # Limits and requests for CPU and memory
          ports:
            - containerPort: {{ .Values.payment.service.targetPort }}  # 80
          livenessProbe:
            httpGet:
              path: {{ .Values.payment.probe.path }}  # /health
              port: {{ .Values.payment.service.targetPort }}  # 80
            initialDelaySeconds: {{ .Values.payment.probe.liveness.initialDelaySeconds }}  # 300
            periodSeconds: {{ .Values.payment.probe.liveness.periodSeconds }}  # 3
          readinessProbe:
            httpGet:
              path: {{ .Values.payment.probe.path }}  # /health
              port: {{ .Values.payment.service.targetPort }}  # 80
            initialDelaySeconds: {{ .Values.payment.probe.readiness.initialDelaySeconds }}  # 180
            periodSeconds: {{ .Values.payment.probe.readiness.periodSeconds }}  # 3
