apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.queueMaster.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    name: {{ .Values.queueMaster.name }}
spec:
  replicas: {{ .Values.queueMaster.replicaCount }}
  selector:
    matchLabels:
      name: {{ .Values.queueMaster.name }}
  template:
    metadata:
      labels:
        name: {{ .Values.queueMaster.name }}
    spec:
      containers:
      - name: {{ .Values.queueMaster.name }}
        image: "{{ .Values.queueMaster.image.repository }}:{{ .Values.queueMaster.image.tag }}"
        env:
          - name: JAVA_OPTS
            value: {{ .Values.queueMaster.env.javaOpts }}
        resources:
          {{- toYaml .Values.queueMaster.resources | nindent 12 }}
        ports:
          - containerPort: {{ .Values.queueMaster.service.targetPort }}
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 300
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 180
          periodSeconds: 3
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
