apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.userDb.name }}
  labels:
    name: {{ .Values.userDb.name }}
  namespace: {{ .Values.global.environment }}
spec:
  ports:
    - port: {{ .Values.userDb.service.port }}
      targetPort: {{ .Values.userDb.service.targetPort }}
  selector:
    name: {{ .Values.userDb.name }}