apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.userDb.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    name: {{ .Values.userDb.name }}
spec:
  ports:
    - port: {{ .Values.userDb.service.port }}
      targetPort: {{ .Values.userDb.service.targetPort }}
      protocol: TCP
  selector:
    name: {{ .Values.userDb.name }}
